version: "3"

tasks:
  clippy:
    cmds:
      - cargo clippy
    silent: true
  api:
    cmds:
      - cargo run --bin bevy-multiplayer-api
    silent: true
  notifs:
    cmds:
      - cargo run --bin bevy-multiplayer-notifs
    silent: true
  server:
    cmds:
      - cargo run --bin bevy-multiplayer-server {{.CLI_ARGS}}
    silent: true
  client:
    cmds:
      - cargo run --bin bevy-multiplayer
    silent: true
