version: "3"

tasks:
  start-agones-cluster:
    cmds:
      - minikube start -p agones --kubernetes-version v1.30.4
    silent: true
  stop-agones-cluster:
    cmds:
      - minikube -p agones stop
    silent: true
  agones-cluster-dashboard:
    cmds:
      - minikube -p agones dashboard
    silent: true
  start-agones-local:
    cmds:
      - bin/sdk-server.linux.amd64 --local
    silent: true
  start-agones:
    cmds:
      - docker run --network=host us-docker.pkg.dev/agones-images/release/agones-sdk:1.44.0 --local
    silent: true

  clippy:
    cmds:
      - cargo clippy
    silent: true
  clean:
    cmds:
      - cargo clean
    silent: true
  really-clean:
    deps: [clean]
    cmds:
      - docker system prune -f
      - docker rmi -f bevy-multiplayer-api
      - docker rmi -f bevy-multiplayer-notifs
      - docker rmi -f bevy-multiplayer-server
      - minikube delete
    silent: true

  api:
    cmds:
      - cargo run --bin bevy-multiplayer-api
    silent: true
  build-api-image:
    cmds:
      - docker buildx build -t bevy-multiplayer-api -f services/api/Dockerfile .
    silent: true
  notifs:
    cmds:
      - cargo run --bin bevy-multiplayer-notifs
    silent: true
  build-notifs-image:
    cmds:
      - docker buildx build -t bevy-multiplayer-notifs -f services/notifs/Dockerfile .
    silent: true
  build-services-images:
    deps: [build-api-image, build-notifs-image]
    silent: true
  start-services:
    dir: services
    cmds:
      # no way to not error if the network already exists ... soooooo
      #- docker network create bevy-multiplayer-default || true
      - docker-compose up
    silent: true
  stop-services:
    dir: services
    cmds:
      - docker-compose stop && docker-compose rm -f
    silent: true

  server:
    cmds:
      - cargo run --bin bevy-multiplayer-server -- {{.CLI_ARGS}}
    silent: true
  build-server-image:
    cmds:
      - docker buildx build -t bevy-multiplayer-server -f game/server/Dockerfile .
    silent: true
  start-local-server:
    cmds:
      - docker run --network=host bevy-multiplayer-server local
    silent: true
  start-agones-server:
    cmds:
      - docker run --network=host bevy-multiplayer-server agones
    silent: true

  client:
    cmds:
      - cargo run --bin bevy-multiplayer
    silent: true
